service: aws-dynamo-ts
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: sa-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:         
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:CreateTable
      Resource: '*'

functions:
  hello:
    handler: dist/src/Users.hello
    events:
      - httpApi:
          path: /
          method: get
  register:
    handler: dist/src/Users.register
    events:
      - httpApi:
          path: /register
          method: post
  login:
    handler: dist/src/auth.login
    events:
      - httpApi:
          path: /login
          method: get
  listUsers:
    handler: dist/src/Users.listUsers
    events:
      - httpApi:
          path: /users
          method: get