service: api-serverless
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: sa-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - arn:aws:dynamodb:sa-east-1:751353583853:table/UsersTable

functions:
  hello:
    handler: src/Users.hello
    events:
      - httpApi:
          path: /
          method: get
  getUsers:
    handler: src/Users.getUsers
    events:
      - httpApi:
          path: /users
          method: get
  register:
    handler: src/Users.register
    events:
      - httpApi:
          path: /register
          method: post

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: UsersTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: username
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH